language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer global install fxp/composer-asset-plugin
  - travis_retry composer install --prefer-source --no-interaction --dev

script: 
  - vendor/bin/codecept run --coverage --coverage-xml

after_script:
  - vendor/bin/php-coveralls -v

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true